### ISSUE TITLE
Need to Create Promotions Model

### ISSUE THREAD

**Issue by bkudler** [CSCI-GA-2820-SU23-001/promotions#3]
**As a** Developer
**I need** to a `Promotions.py` model 
**So that** so that promotions can be created and that resources can return data

**Assumptions:**
- There will be a Promotion class
- A Promotion will have with the following attributes:
   1. name : string, get
   2. start_date : date time, get
   3. end_date : date time, get&set
   4. whole_store : boolean, get&set
   5.  has_been_extended: boolean, get&set
   6.  original_end_date: date time, get&set
   7.  message: string, get&set
   8.  promotion_changes_price: boolean, get&set
- A Promotion will have with the following methods:
  1. is_active: returns whether the promotion is currently active
  2. get_promotional_message: returns pretty print version of name, message and date for instance: "until {end_date} buy {name} one {message}!" or "until July 1st buy five get one free. The sixth one is on us!"
- An instance of a Promotion will belong to a Product, in other words a Promotion will have many Products
**Acceptance Criteria:**

```
A Promotion can be created throwing proper errors. 
A Promotion can be created, read, updated, and deleted in the database
```

**Comment by loixe** [comment]
Do we need a promotion code?

**Comment by bkudler** [comment]
> Do we need a promotion code?

I'm not sure. It doesn't seem like these are by promotions that a user can apply. The description appears to say that promotions apply to products, not to an order, as a product code would. I can't say for sure though. Maybe we can ask the professor or discuss among ourselves?

**Comment by tanaytrivedi** [comment]
We need to add a promotion ID, a name that is user defined need not be unique.

**Comment by bkudler** [comment]
https://github.com/CSCI-GA-2820-SU23-001/promotions/pull/13
