### ISSUE TITLE
Create a Dev and Prod Namespace for the Kubernetes Cluster

### ISSUE THREAD

**Issue by bkudler** [CSCI-GA-2820-SU23-001/promotions#30]
**As a** developer
**I need a** prod and dev namespace
**So that** I can deploy new features to the cloud but have a working version

**Assumptions**
- There are two namespaces in the cluster

**Acceptance Criteria**
GitHub CI can deploy to either prod or dev environment
Development port is: 31001 and the Production port is:
31002

**Comment by tanaytrivedi** [comment]
Added the dev and prod namespace to the cluster. Evidence in picture attached. 
<img width="464" alt="image" src="https://github.com/CSCI-GA-2820-SU23-001/promotions/assets/19849991/c414da63-c6db-4136-8b70-e0aba3c0c862">
