### ISSUE TITLE
Need REST API to Create a Promotion

### ISSUE THREAD

**Issue by bkudler** [CSCI-GA-2820-SU23-001/promotions#5]
**As an** Admin
**I need a** way to create a Promotion
**So that** promotions can exist that can be applied to products

**Assumptions**
- The base URL would be /promotions/create
- This will be a past endpoint and will accept data
- The data accepted will be the attributes for the Promotion
- Hitting this endpoint with correct data will add a new Promotion to the database
- URL should return the newly created Promotion or an error with a meaningful message if there was an issue

Acceptance Criteria
```
Given the server is available
When I call the URL `/promotions/create`
Then it should create a new Promotion and return a Promotion or error using a JSON string in the format:
The Results should look like this

{
    <id> : <value>
    <name>: <value>
    <start_date>: <value>
    <end_date>: <value>
    <is_active>: <value>
    <whole_store>: <value>
    <has_been_extended>: <false>
    <original_end_date>: <end_date>
    <message>: <value>
    <promotion_changes_price>: <value>
}

or 

{
<error>:<message>
}
```

**Comment by tanaytrivedi** [comment]
Add the ID I mentioned in the issue #3 and I am onboard.
