### ISSUE TITLE
Update route.py

### ISSUE THREAD

**Issue by tanaytrivedi** [CSCI-GA-2820-SU23-001/promotions#6]

**Comment by tanaytrivedi** [comment]
As a Developer
I need to update the routes.py file to contain the Flask routes for the Create, Read, Update, Delete and List endpoint.
So that the endpoints can function properly and register in the API.

Assumptions:

We will directly follow the directions given in Slack by Professor Rofrano
Acceptance Criteria:

- requirements.txt, Makefile and setup.cfg match the versions in [this repo](https://github.com/nyu-devops/project-template)
- A pull request identical [to this pull request](https://github.com/nyu-devops/project-template/pull/11) is made

**Comment by tanaytrivedi** [comment]
Did this one wrong. How do i delete this.

**Comment by bkudler** [comment]
you can hit "close issue" in the corner
